# -*- coding: utf-8 -*-
"""Datos_Word.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UGUbSWaPev-g8kXIBwTwYF__AfmHCzc2
"""

!pip install docxtpl -q
!pip install python-docx -q

import pandas as pd
from datetime import datetime
from docxtpl import DocxTemplate

doc = DocxTemplate("plantilla.docx")

nombre = "Edwin Quintero Alzate"
telefono = "(321) 7199749"
correo = "egqa1975@gmail.com"
fecha = datetime.today().strftime("%d/%m/%Y")

print(fecha)

constantes = {'nombre': nombre, 'telefono': telefono, 'correo': correo,
              'fecha': fecha}

print(constantes)

df = pd.read_excel('Alumnos.xlsx')
df

for indice, fila in df.iterrows():
    contenido = {'nombre_alumno':fila["Nombre del Alumno"],'nota_mat': fila['Mat'],
        'nota_fis': fila['Fis'],'nota_qui': fila['Qui']}
    contenido.update(constantes)

    doc.render(contenido)
    doc.save(f"Notas_de_{fila['Nombre del Alumno']}.docx")

    print(contenido)

doc.render(constantes)
doc.save(f"prueba.docx")